spring.application.name=character-stat

spring.datasource.url=jdbc:postgresql://localhost:5432/character_stat
spring.datasource.username=myuser
spring.datasource.password=secret

spring.threads.virtual.enabled=true

spring.sql.init.mode=always